//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOut_Collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOut_Collection()
        {
            this.WorkOut_Active = new HashSet<WorkOut_Active>();
        }
    
        public string WorkOut_Title { get; set; }
        public string WorkOut_Note { get; set; }
        public Nullable<double> Calories_Burn_Per_Minute { get; set; }
        public Nullable<int> Category_id { get; set; }
        public int WorkOut_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOut_Active> WorkOut_Active { get; set; }
        public virtual WorkOut_Category WorkOut_Category { get; set; }
    }
}
